"""Core package exports for concise imports in app and tests."""

from .button_controller import ButtonControllerConfig, dispatch_playback_command, next_command_id, setup_gpio_buttons
from .config import Config
from .constants import (
	DEFAULT_BUTTON_BOUNCE_TIME,
	DEFAULT_BUTTON_LABEL_NEXT_Y_PERCENT,
	DEFAULT_BUTTON_LABEL_PLAY_Y_PERCENT,
	DEFAULT_BUTTON_LABEL_STOP_Y_PERCENT,
	DEFAULT_BUTTON_NEXT_PIN,
	DEFAULT_BUTTON_PLAY_PAUSE_PIN,
	DEFAULT_BUTTON_STOP_PIN,
	DEFAULT_COMMAND_CONFIRM_SECONDS,
	DEFAULT_COVER_RETRY_SECONDS,
	DEFAULT_DISPLAY_X_SHIFT,
	DEFAULT_FB_DEVICE,
	DEFAULT_FONT_BOLD_CANDIDATES,
	DEFAULT_FONT_REGULAR_CANDIDATES,
	DEFAULT_FONT_SYMBOLS_CANDIDATES,
	DEFAULT_HEIGHT,
	DEFAULT_HTTP_TIMEOUT,
	DEFAULT_NO_TRACK_GRACE_SECONDS,
	DEFAULT_PLAYER_NAME,
	DEFAULT_PLEX_SERVER,
	DEFAULT_POLL_SECONDS,
	DEFAULT_PROGRESS_UPDATE_SECONDS,
	DEFAULT_TIMEZONE,
	DEFAULT_TOAST_DURATION_SECONDS,
	DEFAULT_WEATHER_REFRESH_SECONDS,
	DEFAULT_WIDTH,
	TRUTHY_ENV_VALUES,
)
from .display_adapter import DisplayAdapterConfig, DisplayAdapterLogger, create_error_placeholder, try_write_framebuffer, write_fallback_placeholder
from .models import LoopState, PlaybackSnapshot, PlexTrack, RuntimeState, TransitionDecision, TransitionMode, WeatherInfo
from .playback_collector import PlaybackCollectorConfig, PlaybackCollectorDeps, collect_playback_snapshot
from .render_policy import commit_idle_render_state, commit_playing_render_state, resolve_idle_render_plan, resolve_playing_render_plan
from .transition_rules import (
	apply_button_rules,
	apply_transition_decision,
	compute_display_elapsed_ms,
	resolve_transition,
	resolve_wait_timeout,
	should_poll_timeline,
)

__all__ = [
	"ButtonControllerConfig",
	"Config",
	"DisplayAdapterConfig",
	"DisplayAdapterLogger",
	"LoopState",
	"PlaybackCollectorConfig",
	"PlaybackCollectorDeps",
	"PlaybackSnapshot",
	"PlexTrack",
	"RuntimeState",
	"TransitionDecision",
	"TransitionMode",
	"WeatherInfo",
	"apply_button_rules",
	"apply_transition_decision",
	"collect_playback_snapshot",
	"commit_idle_render_state",
	"commit_playing_render_state",
	"compute_display_elapsed_ms",
	"create_error_placeholder",
	"dispatch_playback_command",
	"next_command_id",
	"resolve_idle_render_plan",
	"resolve_playing_render_plan",
	"resolve_transition",
	"resolve_wait_timeout",
	"setup_gpio_buttons",
	"should_poll_timeline",
	"try_write_framebuffer",
	"write_fallback_placeholder",
	"DEFAULT_BUTTON_BOUNCE_TIME",
	"DEFAULT_BUTTON_LABEL_NEXT_Y_PERCENT",
	"DEFAULT_BUTTON_LABEL_PLAY_Y_PERCENT",
	"DEFAULT_BUTTON_LABEL_STOP_Y_PERCENT",
	"DEFAULT_BUTTON_NEXT_PIN",
	"DEFAULT_BUTTON_PLAY_PAUSE_PIN",
	"DEFAULT_BUTTON_STOP_PIN",
	"DEFAULT_COMMAND_CONFIRM_SECONDS",
	"DEFAULT_COVER_RETRY_SECONDS",
	"DEFAULT_DISPLAY_X_SHIFT",
	"DEFAULT_FB_DEVICE",
	"DEFAULT_FONT_BOLD_CANDIDATES",
	"DEFAULT_FONT_REGULAR_CANDIDATES",
	"DEFAULT_FONT_SYMBOLS_CANDIDATES",
	"DEFAULT_HEIGHT",
	"DEFAULT_HTTP_TIMEOUT",
	"DEFAULT_NO_TRACK_GRACE_SECONDS",
	"DEFAULT_PLAYER_NAME",
	"DEFAULT_PLEX_SERVER",
	"DEFAULT_POLL_SECONDS",
	"DEFAULT_PROGRESS_UPDATE_SECONDS",
	"DEFAULT_TIMEZONE",
	"DEFAULT_TOAST_DURATION_SECONDS",
	"DEFAULT_WEATHER_REFRESH_SECONDS",
	"DEFAULT_WIDTH",
	"TRUTHY_ENV_VALUES",
]
